### PR TITLE
Render 404 page for invalid urls.

### PR DESCRIPTION
**Pull request by alanpeabody**

### CODE REVIEW

**Comment by alanpeabody** [comment]
For some reason deploying via the heroku UI was not properly building this release. Pushing to the server via git worked fine though. Anyway, up and working now:

https://o.ello.ninja/notaurl

Do we want any copy tweaks on this?

**Comment by jayzes** [comment]
LGTM! Copy seems fine to start. @caseydoran any thoughts?

**Comment by caseydoran** [comment]
@alanpeabody is that the same copy as the web-app 404? if so, looks good!

**Comment by alanpeabody** [comment]
@caseydoran it is the same copy as the gateway 404, which we moved from mothership. Not sure about webapp...

**Comment by caseydoran** [comment]
Cool.

Casey Doran
Director of Product
ello.co/dcdoran

_The Creators Network_

http://www.commongroundscoffeehouse.com/lodo.html

**Pull request merged**
